version: '3.1'
services:
  elasticsearch-example-client:
    build: .
    environment:
      - ES_CLUSTER_NAME=elasticsearch
      - ES_HOST=els_elasticsearch_1
      - ES_PORT=9300
    # entrypoint: tail -f /etc/hosts
